<script type="text/javascript">
<!--
$(function($) {
<?php if(!$user): ?>
    $( '#login' ).modal({
		keyboard : false,
		backdrop: 'static',
	});
<?php endif; ?>
    $('#login').on('change', '#auth_name', function(e){
        var name = $('#auth_name').val()?
                $('#auth_name').val() : $('#auth_username').val();
        $('#name').html(name);
    });

    $('#login').on('hidden.bs.modal', function (e) {
        
        if ( $('#auth_email').length > 0 && !$('#auth_email').val().length )
        {
            $( '#settings' ).modal({
        		keyboard : false,
        		backdrop: 'static',
        	});
        	$('button[data-dismiss="modal"]', $('#settings')).fadeOut();
        }
    });
});
-->
</script>

<!-- Modal -->
<div class="modal fade in" id="login" tabindex="-1" role="dialog" aria-labelledby="loginLabel" aria-hidden="true">
  <div class="modal-dialog modal-m">
    <div class="modal-content">
      <div class="modal-header">
         <!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button> -->
        <h3 class="modal-title form-signin-heading" id="loginLabel"><?php echo $this->translate('Autenticazione') ?></h3>
      </div>
      <form id="auth" class="form-signin" data-refresh="0" data-async data-validate data-target="#login [name='feedback']" 
        action="<?php echo $this->url('login')?>"
        method="POST">
      <div class="modal-body" style="background-color: #f5f5f5;">
<?php if($user): ?>
        <input type="hidden" id="auth_id" name="id" value="<?php echo $user['id']; ?>">
        <input type="hidden" id="auth_username" name="username" value="<?php echo $user['username']; ?>">
        <input type="hidden" id="auth_name" name="name" value="<?php echo $user['name']; ?>">
        <input type="hidden" id="auth_email" name="email" value="<?php echo $user['email']; ?>">
<?php endif; ?>
        <span name="feedback"></span>
        
         <div class="form-group">
            <label for="inputUsername" class="sr-only"><?php echo $this->translate('Nome Utente') ?></label>
                <input name="username" data-validation="required" 
                    data-validation-error-msg="Questo campo è obbligatorio!" 
                    id="inputUsername" class="form-control" placeholder="<?php echo $this->translate('Nome Utente') ?>">
         </div>
         
         <div class="form-group">
            <label for="inputPassword" class="sr-only"><?php echo $this->translate('Password') ?></label>
                <input name="password" data-validation="required" type="password" 
                    data-validation-error-msg="Questo campo è obbligatorio!" 
                    id="inputPassword" class="form-control" placeholder="<?php echo $this->translate('Password') ?>">
        </div>
        
        <div class="checkbox">
          <label for="checkboxRemember"><?php echo $this->translate('Ricordami') ?></label>
                <input  name="rememberme" id="checkboxRemember" type="checkbox" value="1" checked="checked">
        </div>
        <button class="btn btn-primary btn-block" type="submit"><?php echo $this->translate('Entra') ?></button>
      </div>
    </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->