<script type="text/javascript">
<!--
// $( '#settings' ).modal({
// 	keyboard : false,
// 	backdrop: 'static',
// });

$(function($) {
    $('#settings').on('show.bs.modal', function (e) {
    	$('button[data-dismiss="modal"]', $('#settings')).fadeIn();
    	$('input[name="id"]', $('#settings')).val($('#auth_id').val());
    	$('input[name="name"]', $('#settings')).val($('#auth_name').val());
    	$('input[name="username"]', $('#settings')).val($('#auth_username').val());
    	$('input[name="email_confirmation"]', $('#settings'))
    	   .add('input[name="email"]', $('#settings'))
    	       .val($('#auth_email').val());
    });
});
//-->
</script>

<!-- Modal -->
<div class="modal fade in" id="settings" tabindex="-1" role="dialog" aria-labelledby="settingsLabel" aria-hidden="true">
  <div class="modal-dialog modal-m">
    <div class="modal-content">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title form-signin-heading" id="settingsLabel">Impostazioni Utente</h4>
      </div>
      <form id="profile" class="form-settings" data-async data-validate data-target="#settings [name='feedback']" 
        action="<?php echo $this->url('test', array('controller' => 'frontend', 'action'=>'settings'))?>" 
        method="POST">
      <div class="modal-body">
         <span name="feedback">
             <p class="alert alert-warning">
                <b>Caronte</b> richiede l'email di lavoro!<br/>
                <u><b>Può esser richiesto l'invio di mail</b></u> per comunicare con gli operatori
             </p>
         </span>
         <input name="id" type="hidden">
          <div class="form-group">
            <label for="inputUsername">Nome Utente:</label>
            <input name="username" type="username" id="inputUsername" class="form-control"
                placeholder="Nome Utente" disabled="disabled">
          </div>
          <div class="form-group">
            <label for="inputName">Nome:</label>
            <input name="name" type="name" id="inputName" class="form-control"
                data-validation-error-msg="Inserire un nome non più lungo di 25 caratteri"
                placeholder="Nome" data-validation-length="max25">
          </div>
          <div class="form-group">
            <label for="inputEmail">Email:</label>
            <input name="email_confirmation" data-validation="email required" id="inputEmail"
                data-validation-error-msg="Inserire un indirizzo email valido" class="form-control"
                placeholder="Il tuo indirizzo email">
          </div>
          <div class="form-group">
            <label for="inputEmail">Conferma Email:</label>
<!--            <input name="email2" type="email" title="Riscrivere l'email per conferma!" id="inputEmail" class="form-control" placeholder="Conferma la tua email" required="required"> -->
                <input name="email" data-validation="confirmation required" data-validation-error-msg="Riscrivere l'email per conferma!" id="inputEmail" class="form-control" placeholder="Conferma la tua email">
          </div>
          <center>
          <button type="submit" class="btn btn-primary">Salva</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
          </center>
      </div>
    </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->