<script type="text/javascript">
<!--
// $( '#settings' ).modal({
// 	keyboard : false,
// 	backdrop: 'static',
// });

$(function($) {
    $('#settings').on('show.bs.modal', function (e) {
    	$('button[data-dismiss="modal"]', $('#settings')).fadeIn();
    	$('input[name="id"]', $('#settings')).val($('#auth_id').val());
    	$('input[name="name"]', $('#settings')).val($('#auth_name').val());
    	$('input[name="username"]', $('#settings')).val($('#auth_username').val());
    	$('input[name="email_confirmation"]', $('#settings'))
    	   .add('input[name="email"]', $('#settings'))
    	       .val($('#auth_email').val());
    });
});
//-->
</script>

<!-- Modal -->
<div class="modal fade in" id="settings" tabindex="-1" role="dialog" aria-labelledby="settingsLabel" aria-hidden="true">
  <div class="modal-dialog modal-m">
    <div class="modal-content">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title form-signin-heading text-center" id="settingsLabel"><?php echo $this->translate('Impostazioni Utente') ?></h4>
      </div>
      <form id="profile" class="form-settings" data-refresh="0" data-async data-validate data-target="#settings [name='feedback']" 
        action="<?php echo $this->url('test', array('controller' => 'frontend', 'action'=>'settings'))?>" 
        method="POST">
      <div class="modal-body">
         <span name="feedback">
             <p class="alert alert-warning">
                <b><?php echo $this->translate('Hd0') ?></b> <?php echo $this->translate('richiede l\'email di lavoro!') ?><br/>
                <u><b><?php echo $this->translate('Può esser richiesto l\'invio di mail') ?></b></u> <?php echo $this->translate('per comunicare con gli operatori') ?>
             </p>
         </span>
         <input name="id" type="hidden">
          <div class="form-group">
            <label for="inputUsername"><?php echo $this->translate('Nome Utente') ?>:</label>
            <input name="username" type="username" id="inputUsername" class="form-control"
                placeholder="<?php echo $this->translate('Nome Utente') ?>" disabled="disabled">
          </div>
          <div class="form-group">
            <label for="inputName"><?php echo $this->translate('Nome') ?>:</label>
            <input name="name" type="name" id="inputName" class="form-control"
                data-validation-error-msg="Attesi massimo di 30 caratteri"
                placeholder="<?php echo $this->translate('Nome') ?>" data-validation="length" 
                data-validation-length="max30">
          </div>
          <div class="form-group">
            <label for="inputEmail"><?php echo $this->translate('Email') ?>:</label>
            <input name="email_confirmation" data-validation="email domain required" id="inputEmail"
                data-validation-error-msg="Inserire una email di lavoro valida (@iper.it, @ortofin.it o @unes.it)" class="form-control"
                placeholder="<?php echo $this->translate('Il tuo indirizzo email') ?>">
          </div>
          <div class="form-group">
            <label for="inputEmail"><?php echo $this->translate('Conferma Email') ?>:</label>
                <input name="email" data-validation="confirmation required" 
                    data-validation-error-msg="Riscrivere l'email per conferma!" id="inputEmail" 
                    class="form-control" placeholder="<?php echo $this->translate('Conferma la tua email') ?>">
          </div>
          <center>
          <button type="submit" class="btn btn-primary"><?php echo $this->translate('Salva') ?></button>
          <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Annulla') ?></button>
          </center>
      </div>
    </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->