<script type="text/javascript">
<!--
a = {
	keyboard : false,
	backdrop: 'static'
};
//-->
</script>

<!-- Modal -->
<div class="modal fade in" id="settings" tabindex="-1" role="dialog" aria-labelledby="settingsLabel" aria-hidden="true">
  <div class="modal-dialog modal-m">
    <div class="modal-content">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title form-signin-heading" id="settingsLabel">Impostazioni Utente</h4>
      </div>
      <form class="form-signin" action="/hd0/test/frontend/settings" method="post">
      <div class="modal-body">
          <div class="form-group">
            <label for="inputUsername">Nome Utente:</label>
            <input name="username" type="username" id="inputUsername" class="form-control" placeholder="Nome Utente" value="Guest" disabled="disabled">
          </div>
          <div class="form-group">
            <label for="inputEmail">Email (*):</label>
            <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Indirizzo Email" required="required" autofocus="">
          </div>
          
          <p>(*): Il campo è obbligatorio</p>
          
          <button type="submit" class="btn btn-primary">Salva</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
      </div>
    </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->