<!-- Pref Modal -->
<script type="text/javascript">
<!--
function priorityButton (e) {
   var $button = e? $(this) : $('#priority .btn');
   var $input = $button.find('input:checkbox');
   if (e){
	   $input.prop("checked", !$input.prop("checked"));
   }
   if ($input.prop("checked"))
   {
	   $button.removeClass("btn-default").addClass("btn-danger");
	   $button.find(".glyphicon").removeClass("alert-danger");
	   if (!e) $button.addClass('active');
   } else {
	   $button.addClass("btn-default").removeClass("btn-danger");
	   $button.find(".glyphicon").addClass("alert-danger");
	   if (!e) $button.removeClass('active');
   }
}

$( function ($) {
       var $modal = $('#ticketModal');
    	
       $modal.on('show.bs.modal', function (e) {
            var $related = $(e.relatedTarget);
            var $current = $(e.currentTarget);
            var assignments = { // true: attr false: prop
        			"queue-id"       :   true,
        			"queue-name"     :   true,
        			"queue-color"    :   true,
        			"id"             :   true,
        			"ticket-priority":   false,
        			"ticket-title"   :   false,
        			"ticket-desc"    :   false,
        	};
            
            if ($related.length)
            {
                $.each(assignments, function(index, attr){

                    var data = (attr)?$related.data(index):$related.prop('data-'+index);

                    $current.find('input:hidden[name="'+index+'"]').prop('value',data);

                    var $items = $current.find('*[data-name="'+index+'"][data-prop]');
                     
                    $items.each(function(k, item){
                    	  var $item = $(item);
                    	  $item.prop($item.data('prop'), data);
                        });
                     
                    $items = $current.find('*[data-name="'+index+'"]').not('*[data-prop]');
                    $items.text(data);

                    $current.find('.'+index).removeClass(removeMetaColors).addClass(data);
                });
                $current.find('#ticketQueue').text( $('#ticketQueue').text().trimToLength(10) );
                
                if (parseInt($current.find('input:hidden[name="id"]').val())>0){
                    
                	$current.find('.articoli').removeClass('hidden');
                	$current.find('input').add($current.find('textarea')).each(
                        	function(){this.disabled=true});
                	$("#priority .btn").addClass('disabled');
                	$("#send").add("#cancel").addClass('hidden');
                	$("#close").removeClass('hidden');
                }else{
                    
                	$current.find('.articoli').addClass('hidden');
                	$current.find('input').add($current.find('textarea')).each(
                        	function(){this.disabled=false});
                	$("#priority .btn").removeClass('disabled');
                	$("#send").add("#cancel").removeClass('hidden');
                	$("#close").addClass('hidden');
            	}
            }
            colorize($current);
            priorityButton();
            $("#priority .btn").on('click', priorityButton);
        });
   	
/* $("#ticketModal").on ("change", "#tagCloud :checkbox", function(e) {
	var buttons = $(this).siblings("[data-toggle='buttons']").eq(0);
	$('label < :checked', buttons).eq(0).button('toggle').find(':checkbox').prop('checked');
});

$("#tagCloud [data-toggle='buttons']").change(function (e) {
	var tag = $("#tagCloud :checkbox").map(function () {
        return +$(this).is(':checked');
    }).get(); 
    console.log(tag);
}); */
});
//-->
</script>
<div id="ticketModal" class="modal modal-sm fade" tabindex="-2" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
		    <form method="post" data-validate data-async data-target="#ticketModal [name='feedback']" method="POST"
		      action="<?php echo $this->url('test', array('controller' => 'frontend', 'action'=>'saveTicket'))?>" >
		    
		    <div class="zero-clipboard" data-name="queue-name" data-prop="title" title="Queue" >
		      <span class="queue-color btn-clipboard" >
		          <span id="ticketQueue" data-name="queue-name"></span>
		          <span class="glyphicon glyphicon-tag"></span>
	          </span>
          </div>
		    
			<div class="modal-header b-grey">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<div class="row">
    				<div class="col-md-9">	
    				    <input type="text" class="form-control" name="title" 
    				        data-name="ticket-title" data-prop="value" placeholder="Titolo..."
    				        data-validation-error-msg="Campo obbligatorio non superiore a 50 caratteri"
                            data-validation="required length" 
                            data-validation-length="max50"
				        />
    				</div>
				</div>
			</div>
			<div class="modal-body">
    			<div class="row">
        			<span name="feedback"></span>
        			<span name="hint"></span>
    
    				<input name="id" type="hidden" value="0" />
    				<input name="queue-id" type="hidden" value="" />
    				<input name="queue-name" type="hidden" value="" />
    				<input name="queue-color" type="hidden" value="" />
    				
    				<div class="col-md-9">
        				    
   				        <textarea class="col-md-12 form-control" name="description"
   				            data-name="ticket-desc" data-prop="value" placeholder="Descrizione..."
     				        data-validation-error-msg="Testo atteso non inferiore a 50 caratteri"
                            data-validation="length" 
                            data-validation-length="min50"></textarea>
<!-- start@wizard -->
                        <div class="col-md-12 form-control wizard hidden">
                            <div id="rootwizard">
                            	<div class="navbar">
                            	  <div class="navbar-inner">
                                	<ul>
                            	  	<li><a href="#tab1" data-toggle="tab">1# Domanda</a></li>
                            		<li><a href="#tab2" data-toggle="tab">2# Domanda</a></li>
                            		<li><a href="#tab3" data-toggle="tab">3# Domanda</a></li>
                            	   </ul>
                            	  </div>
                            	</div>
                                <div id="bar" class="progress progress-striped active">
                                   <div class="bar progress-bar"></div>
                                </div>
                            	<div class="tab-content">
                            	    <div class="tab-pane" id="tab1">
                            	      1
                            	    </div>
                            	    <div class="tab-pane" id="tab2">
                            	      2
                            	    </div>
                            		<div class="tab-pane" id="tab3">
                            		  3
                            	    </div>
                            		<ul class="pager wizard">
                            			<li class="previous first" style="display:none;"><a href="#">Primo</a></li>
                            			<li class="previous"><a href="#">Indietro</a></li>
                            <!-- 		<li class="next last" style="display:none;"><a href="#">Ultimo</a></li> -->
                            		  	<li class="next"><a href="#">Avanti</a></li>
                            		  	<li class="next finish" style="display:none;"><a href="javascript:;">Pubblica</a></li>
                            		</ul>
                            	</div>	
                            </div>
                        </div> 
<!-- end@wizard -->
    				</div>
    				<div class="col-md-3">
    				    <div id="priority" data-toggle="buttons">
    				        <label title="Non posso lavorare!" class="btn btn-default"><input data-name="ticket-priority" data-prop="checked" type="checkbox" />Urgente <span class="glyphicon glyphicon-exclamation-sign alert-danger"></span></label>
    				    </div>
    				</div>
<!-- start@articles -->
    				<div class="col-md-12">
    				    <div class="well articoli">
    				        <h4><span title="articoli" class="glyphicon glyphicon-comment"></span> Articoli</h4>
    				        <div class="panel-group" id="articoli" role="tablist" aria-multiselectable="true">
                              <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="h_ticketCode_1">
                                  <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#articoli" href="#b_ticketCode_1" aria-expanded="false" aria-controls="b_ticketCode_1">
                                      Luca - Zenatek (gg/mm/aaaa - hh:mm)
                                      <span class="badge alert-info pull-right">2 <span title="allegati" class="glyphicon glyphicon-paperclip"></span></span>
                                    </a>
                                  </h4>
                                </div>
                                <div id="b_ticketCode_1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="h_ticketCode_1">
                                  <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                                    <div class="attachmentsList col-md-12 form-control">
                				        <div>
                    				        <ul>
                    				            <li>
                    				                <span title="scarica" class="glyphicon glyphicon-download"></span><a>screenshot.jpg</a><small class="pull-right">96 KB</small>
                    				            </li>
                    				            <li>
                    				                <span title="scarica" class="glyphicon glyphicon-download"></span><a>screenshot(1).jpg</a><small class="pull-right">198 KB</small>
                    				            </li>
                    				        </ul>
                				        </div>
                				    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="h_ticketCode_2">
                                  <h4 class="panel-title">
                                    <a class="collapsed" data-toggle="collapse" data-parent="#articoli" href="#b_ticketCode_2" aria-expanded="false" aria-controls="b_ticketCode_2">
                                      Fabio - Finiper (gg/mm/aaaa - hh:mm)
                                      <span class="badge alert-info pull-right">1 <span title="allegati" class="glyphicon glyphicon-paperclip"></span></span>
                                    </a>
                                  </h4>
                                </div>
                                <div id="b_ticketCode_2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="h_ticketCode_2">
                                  <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                                    <div class="attachmentsList col-md-12 form-control">
                				        <div>
                    				        <ul>
                    				            <li>
                    				                <span title="scarica" class="glyphicon glyphicon-download"></span><a>screenshot.jpg</a><small class="pull-right">86 KB</small>
                    				            </li>
                    				        </ul>
                				        </div>
                				    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="h_ticketCode_3">
                                  <h4 class="panel-title">
                                    <a class="collapsed" data-toggle="collapse" data-parent="#articoli" href="#b_ticketCode_3" aria-expanded="false" aria-controls="b_ticketCode_3">
                                        Luca - Zenatek (gg/mm/aaaa - hh:mm)
                                    </a>
                                  </h4>
                                </div>
                                <div id="b_ticketCode_3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="h_ticketCode_3">
                                  <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                                  </div>
                                </div>
                              </div>
                            </div>
    				    </div>
    				</div>
<!-- end@articles -->
				</div>
            </div>
			<div class="modal-footer b-grey">
			     <!-- if wizards disabled="disabled" che lo attiva lui -->
				<button id="send" type="submit" class="btn btn-info">
				    <span class="glyphicon glyphicon-send"></span> Pubblica
                </button>
				<button id="cancel" type="button" class="btn btn-default" data-dismiss="modal">
				    Annulla
                </button>
                <button id="close" type="button" class="btn btn-default hidden" data-dismiss="modal">
				    Chiudi
                </button>
			</div>
		</div>
		</form>
	</div>
</div>
    				