<!-- Pref Modal -->
<script type="text/javascript">
<!--
function priorityButton (e) {
   var $button = e? $(this) : $('#priority .btn');
   var $input = $button.find('input:checkbox');
   if (e){
	   $input.prop("checked", !$input.prop("checked"));
   }
   if ($input.prop("checked"))
   {
	   $button.removeClass("btn-default").addClass("btn-danger");
	   $button.find(".glyphicon").removeClass("alert-danger");
	   if (!e) $button.addClass('active');
   } else {
	   $button.addClass("btn-default").removeClass("btn-danger");
	   $button.find(".glyphicon").addClass("alert-danger");
	   if (!e) $button.removeClass('active');
   }
}

function loadArticles ($current) {
	var id = $current.find('input[name="id"]').val();
	var serviceId = $current.find('input[name="service-id"]').val();
	
    var $target = $('#articoli');
    var request = {id : id, 'service-id': serviceId};
    var url = '<?php echo $this->url('test', array('controller' => 'frontend', 'action'=>'getArticles')); ?>';
    
    $.ajax({
        type: 'post',
        url: url,
        data: request,
        success: function (data, status) {
        	window.console&&console.log(data);
            return showArticles (data, status, $target, $current );
        }
    });
}

function showArticles (articoli, status, $target, $current)
{
	$articolo = $target.find('.mock');
	$articolo.siblings().remove();

	var addArticle = "Per pubblicare nuovi aggiornamenti invia una mail (anche con allegati) dal tuo indirizzo di posta <b>%mail%</b> incollando come <b>Oggetto</b> della mail quanto segue: <br/><b><u>Re: Subject [Ticket#%num%]</u></b>";
	var num = $current.find('input[name="num"]').val();
	var mail = $('#auth_email').val();
	addArticle = addArticle.replace('%mail%',mail).replace('%num%',num);

    $("a[data-toggle='alert']").on('click', function(e){
             var alert = {'alert-info': addArticle};
             alertHint( $current.find('span[name="feedback"]'), alert );
        });
	
	$.each(articoli, function(k,a){
			// create		  
	        var $clone = $articolo.clone().removeClass('mock').removeClass('hidden');
	        $target.prepend(updateArticle(a, $clone));
		});
	$target.find('[role="tabpanel"]:first').collapse('show');
}

function updateArticle (a, $articolo)
{
	$articolo.find('.panel-heading')
	   .attr('id', 'h_a'+ a['ArticleID']);
	$articolo.find('a[aria-controls]')
	   .attr('aria-controls', 'a'+ a['ArticleID'])
	   .attr('href', "#"+ 'a'+ a['ArticleID']);
	$articolo.find('span[data-name="authorName"]')
	   .text(a['FromRealname']);
	$articolo.find('span[data-name="created"]')
	   .text(a['Created']);
	   
	$articolo.find('[role="tabpanel"]')
	   .attr('id', 'a'+ a['ArticleID'])
	   .attr('aria-labelledby', 'h_a'+ a['ArticleID']);
	$articolo.find('span[data-name="body"]')
	   .empty().html(a['Body']);
	return $articolo;
}

$( function ($) {
       var $modal = $('#ticketModal');
    	
       $modal.on('show.bs.modal', function (e) {
            var $related = $(e.relatedTarget);
            var $current = $(e.currentTarget);

            var assignments = { // true: attr false: prop
            		"service-id"     :   true,
        			"queue-id"       :   true,
        			"queue-name"     :   true,
        			"queue-color"    :   true,
        			"id"             :   true,
        			"num"            :   true,
        			"articles"       :   true,
        			"ticket-priority":   false,
        			"ticket-title"   :   false,
        			"ticket-desc"    :   false,
        	};
            
            if ($related.length)
            {
                $.each(assignments, function(index, attr){

                    var data = (attr)?$related.data(index):$related.prop('data-'+index);

                    $current.find('input:hidden[name="'+index+'"]').prop('value',data);

                    var $items = $current.find('*[data-name="'+index+'"][data-prop]');
                     
                    $items.each(function(k, item){
                    	  var $item = $(item);
                    	  $item.prop($item.data('prop'), data);
                        });
                     
                    $items = $current.find('*[data-name="'+index+'"]').not('*[data-prop]');
                    $items.text(data);

                    $current.find('.'+index).removeClass(removeMetaColors).addClass(data);
                });
                
                $current.find('#ticketQueue').text( $('#ticketQueue').text().trimToLength(10) );
                
                if (parseInt($current.find('input:hidden[name="id"]').val())>0){

                    // mostra box articoli
                	$current.find('.articoli').removeClass('hidden');
                	if(parseInt($current.find('input:hidden[name="articles"]').val())>0)
                		$('.articoli').removeClass('hidden');
                	else
                		$('.articoli').addClass('hidden');
                	// blocca gli input
                	$current.find('input').add($current.find('textarea')).each(
                        	function(){this.disabled=true;});
                	$("#priority .btn").addClass('disabled');
                	// bottoni sono per chiusura
                	$("#send").add("#cancel").addClass('hidden');
                	$("#close").removeClass('hidden');
                	// popola articoli
                    loadArticles($current);
                    // reset articoli
                    $current.find('#articoli [role="tabpanel"]').collapse('hide');
                }else{

                    // nascondi box articoli
                	$current.find('.articoli').addClass('hidden');
                	// abilita gli input
                	$current.find('input').add($current.find('textarea')).each(
                        	function(){this.disabled=false;});
                	// bottoni per il submit
                	$("#priority .btn").removeClass('disabled');
                	$("#send").add("#cancel").removeClass('hidden');
                	$("#close").addClass('hidden');
            	}
            }
            
            colorize($current);
            $('.alert', $current.find('span[name="feedback"]') ).alert('close');
            priorityButton();
            $("#priority .btn").on('click', priorityButton);
        });
   	
/* $("#ticketModal").on ("change", "#tagCloud :checkbox", function(e) {
	var buttons = $(this).siblings("[data-toggle='buttons']").eq(0);
	$('label < :checked', buttons).eq(0).button('toggle').find(':checkbox').prop('checked');
});

$("#tagCloud [data-toggle='buttons']").change(function (e) {
	var tag = $("#tagCloud :checkbox").map(function () {
        return +$(this).is(':checked');
    }).get(); 
    console.log(tag);
}); */
});
//-->
</script>
<div id="ticketModal" class="modal fade" tabindex="-2" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
		    <form method="post" data-validate data-refresh="5000" data-async data-target="#ticketModal [name='feedback']" method="POST"
		      action="<?php echo $this->url('test', array('controller' => 'frontend', 'action'=>'saveTicket'))?>" >
		    
		    <div class="zero-clipboard" data-name="queue-name" data-prop="title" title="Queue" >
		      <span class="queue-color btn-clipboard" >
		          <span id="ticketQueue" data-name="queue-name"></span>
		          <span class="glyphicon glyphicon-tag"></span>
	          </span>
          </div>
		    
			<div class="modal-header b-grey">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<div class="row">
    				<div class="col-md-9">	
    				    <input type="text" class="form-control" name="title" 
    				        data-name="ticket-title" data-prop="value" placeholder="Titolo..."
    				        data-validation-error-msg="Campo obbligatorio non superiore a 50 caratteri"
                            data-validation="required length" 
                            data-validation-length="max50"
				        />
    				</div>
				</div>
			</div>
			<div class="modal-body">
    			<div class="row">
        			<span name="feedback"></span>
        			<span name="hint"></span>
    
    				<input name="id" type="hidden" value="0" />
    				<input name="num" type="hidden" value="0" />
    				<input name="service-id" type="hidden" value="" />
    				<input name="queue-id" type="hidden" value="" />
    				<input name="queue-name" type="hidden" value="" />
    				<input name="queue-color" type="hidden" value="" />
    				<input name="articles" type="hidden" value="" />
    				
    				<div class="col-md-9">
        				    
   				        <textarea class="col-md-12 form-control" name="description"
   				            data-name="ticket-desc" data-prop="value" placeholder="Descrizione..."
     				        data-validation-error-msg="Testo atteso non inferiore a 50 caratteri"
                            data-validation="length" 
                            data-validation-length="min50"></textarea>
<!-- start@wizard -->
                        <div class="col-md-12 form-control wizard hidden">
                            <div id="rootwizard">
                            	<div class="navbar">
                            	  <div class="navbar-inner">
                                	<ul>
                            	  	<li><a href="#tab1" data-toggle="tab">1# Domanda</a></li>
                            		<li><a href="#tab2" data-toggle="tab">2# Domanda</a></li>
                            		<li><a href="#tab3" data-toggle="tab">3# Domanda</a></li>
                            	   </ul>
                            	  </div>
                            	</div>
                                <div id="bar" class="progress progress-striped active">
                                   <div class="bar progress-bar"></div>
                                </div>
                            	<div class="tab-content">
                            	    <div class="tab-pane" id="tab1">
                            	      1
                            	    </div>
                            	    <div class="tab-pane" id="tab2">
                            	      2
                            	    </div>
                            		<div class="tab-pane" id="tab3">
                            		  3
                            	    </div>
                            		<ul class="pager wizard">
                            			<li class="previous first" style="display:none;"><a href="#">Primo</a></li>
                            			<li class="previous"><a href="#">Indietro</a></li>
                            <!-- 		<li class="next last" style="display:none;"><a href="#">Ultimo</a></li> -->
                            		  	<li class="next"><a href="#">Avanti</a></li>
                            		  	<li class="next finish" style="display:none;"><a href="javascript:;">Pubblica</a></li>
                            		</ul>
                            	</div>	
                            </div>
                        </div> 
<!-- end@wizard -->
    				</div>
    				<div class="col-md-3">
    				    <div id="priority" data-toggle="buttons">
    				        <label title="Non posso lavorare!" class="btn btn-default"><input name="priority" data-name="ticket-priority" data-prop="checked" type="checkbox" />Bloccante <span class="glyphicon glyphicon-exclamation-sign alert-danger"></span></label>
    				    </div>
    				</div>
<!-- start@articles -->
    				<div class="col-md-12">
    				
    				     <div class="well alert articoli">
                            <h4 class="article-title"><span title="articoli" class="glyphicon glyphicon-comment"></span> Aggiornamenti</h4>
    				        <p class="text-center"><em><a data-toggle="alert"
			                ><b>[Demo]</b> Come pubblicare un nuovo Aggiornamento ...</a></em></p>
			                
			                <div class="panel-group" id="articoli" role="tablist" aria-multiselectable="true">
			                     <div class="panel panel-default mock hidden">
			                         <div class="panel-heading" role="tab" id="h_a0">
			                             <h4 class="panel-title">
			                                <a data-toggle="collapse" data-parent="#articoli" href="#a0" aria-expanded="false" aria-controls="a0">
                                                Da: <span data-name="authorName">Autore</span>
                                            </a>
                                            <em class="pull-right small"><span data-name="created">aaaa-mm-gg hh:mm:ss</span></em>
                                         </h4>
			                         </div>
			                         <div id="a0" class="panel-collapse collapse" role="tabpanel" aria-labelledby="h_a0">
                                          <div class="panel-body">
                                            <span data-name="body">Testo</span>
                                          </div>
			                         </div>
			                     </div>
			                </div>    				     
    				    </div>
    				</div>
<!-- end@articles -->
				</div>
            </div>
			<div class="modal-footer b-grey">
			     <!-- if wizards disabled="disabled" che lo attiva lui -->
				<button id="send" type="submit" class="btn btn-info">
				    <span class="glyphicon glyphicon-send"></span> Pubblica
                </button>
				<button id="cancel" type="button" class="btn btn-default" data-dismiss="modal">
				    Annulla
                </button>
                <button id="close" type="button" class="btn btn-default hidden" data-dismiss="modal">
				    Chiudi
                </button>
			</div>
		</form>
		</div>
	</div>
</div>    				