<script type="text/javascript">
<!--
$(function($) {
    $( '#welcome' ).modal({
	});
<?php if(!$user): ?>
    $('#welcome').on('hidden.bs.modal', function (e) {
        if (e) {
            $( '#login' ).modal({
                keyboard : false,
                backdrop: 'static',
            });
        }
    });
<?php endif; ?>
});
-->
</script>

<!-- Modal -->
<div class="modal fade in" id="welcome" tabindex="-1" role="dialog" aria-labelledby="loginLabel" aria-hidden="true">
  
  <!--  <div class="modal-dialog visible-lg-modal-xl visible-md-modal-xl visible-sm-modal-l visible-xs-modal-m"> -->
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #f5f5f5;">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title form-signin-heading text-center" id="loginLabel"><?php echo $this->translate('Benvenuto/a nel servizio di Help Desk') ?></h3>
      </div>
        <div class="modal-body">
            <div class="row" style="margin-top: 20px;">
                <div class="col-md-7 col-md-offset-1">
                <h4>
                    <?php echo sprintf( $this->translate('
                            Benvenuto, questa è la tua interfaccia al servizio %s dedicato agli utenti di %s!'),
                       'Help Desk', 'Iper Montebello');?>
                   <br />
                    <?php echo $this->translate('
                            Grazie a questa applicazione puoi accedere con una unica interfaccia a ');
                    echo '<span class="strong">'.$this->translate('tutti servizi di assistenza').'</span>';
                    echo sprintf( $this->translate('
                            erogati dal %s tramite un qualsiasi browser http,
                            inviando una opportuna segnalazione (trouble ticket).'),
                        'S.I. Gruppo Iper');
                    ?>
                </h4>
                <h4>
                <?php echo $this->translate("
                            La tua segnalazione determinerà l'analisi e l’identificazione
                            delle cause delle anomalie e l'attivazione di tutte le azioni
                            necessarie alla rimozione delle stesse, per il ripristino 
                            delle corrette funzionalità operative.");?>
                </h4>
                <h4><ul><li>
                    <?php echo $this->translate('
                            identificazione utente');?>
                    </li><li>
                        <?php echo $this->translate('
                            <b>registrazione</b> del trouble ticket relativo alla <b>segnalazione</b>');?>
                    </li><li>
                        <?php echo $this->translate('
                            <b>presa in carico</b> ed <b>analisi</b> del ticket');?>
                    </li><li>
                        <?php echo $this->translate('
                            assegnazione del ticket a personale con competenze specifiche');?>
                    </li><li>
                        <?php echo $this->translate('
                            avorazione e <b>risoluzione</b> (mediante eventuale escalation)');?>
                    </li><li>
                        <?php echo $this->translate('
                            <b>chiusura</b> del ticket');?>
                    </li></ul>
                </h4>
                </div>
                <div class="col-md-3">
                    <img src="img/zenatek.png" width="100%" height="100%">
                </div>
            </div>
            
            <div class="row col-md-10 col-md-offset-1" style="margin-top: 20px;">    
            <?php if(!$user): ?>
            <button class="btn btn-primary btn-lg btn-block" type="button" data-dismiss="modal"><?php echo $this->translate('Entra') ?></button>
            <?php else: ?>
            <button class="btn btn-success btn-lg btn-block" type="button" data-dismiss="modal"><?php echo $this->translate('Continua') ?></button>
            <?php endif; ?>
            </div>
        </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
 
</div><!-- /.modal -->