<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
$env = getenv('APP_ENV') ?: 'production';

$modules = array (
		'DoctrineModule',
		'DoctrineORMModule',
		'Application',
		'Test',
        'Home'
);

if (false && $env == 'development') {
	$modules[] = 'BjyProfiler';
	$modules[] = 'ZendDeveloperTools';
}
        
return array(
		'modules' => $modules,        
        
        'module_listener_options' => array(
            'module_paths' => array(
            './module',
            './vendor'
        ),
            
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    )
);
