<?php
/**
 *      ## SOAP 3
 * 
 *      ## Backporting old IE ver ##
 *      http://jquery.com/browser-support/
 *      
 *      ## Boostrap3 supporting IE7 ##
 *      (1)(2) http://www.extremecss.com/making-twitter-bootstrap-3-compatible-with-internet-explorer-7-and-below/
 *      (3) http://stackoverflow.com/questions/14793332/problems-with-ie7-and-foundation-3-using-boxsizing-htc
 *      
 *      (1) bootstrap.css +
 *              *behavior: url(/js/boxsizing.htc);
 *          download boxsizing.htc and (if troubles) comment line 53
 *      &&
 *      (2) <header> +
 *          <link href="/css/bootstrap-ie7.css" rel="stylesheet"> // doesnt Work!!!
 *      &&
 *      (3) .htaccess +
 *          AddType text/x-component .htc
 *      
 *      ## Html Conditions to distinguis ##
 *      http://www.quirksmode.org/css/condcom.html
 *      http://www.positioniseverything.net/articles/cc-plus.html
 *      
 *      ## IE7 css properties ##
 *      http://stackoverflow.com/questions/10981767/clean-css-fix-of-ie7s-float-right-drop-bug
 */


echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Finiper - '. $this->translate('Caronte'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        //$enbedded_bootstrap_css = file_get_contents('public/css/bootstrap.css');
        //$this->headStyle()->appendStyle($enbedded_bootstrap_css, array('conditional' => 'lt IE 8'));
        //echo $this->headStyle();
        
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css', 'screen')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-ie7.css', 'screen', 'lt IE 8')

                        ->appendStylesheet($this->basePath() . '/css/glyphicons-ie7.less', 'screen', 'lt IE 8')
                        ->appendStylesheet($this->basePath() . '/css/glyphicons-ie7.css', 'screen', 'lt IE 8')
                        ->appendStylesheet($this->basePath() . '/css/sortable.css')
                        ->appendStylesheet($this->basePath() . '/css/style.css')
                        ->appendStylesheet($this->basePath() . '/css/style-ie.css', 'screen', 'IE')
        ;?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            
            // http://formvalidator.net/index.html
            ->prependFile($this->basePath() . '/js/security.js')
            ->prependFile($this->basePath() . '/js/date.js')
            ->prependFile($this->basePath() . '/js/jquery.form-validator.min.js')
            
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',  'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/modernizr.foundation.js', 'text/javascript', array('conditional' => 'lt IE 8',))

            ->appendFile($this->basePath() . '/js/jquery-sortable.js', 'text/javascript', array('conditional' => '!IE',))
            ->appendFile($this->basePath() . '/js/jquery-sortable-mirror.js', 'text/javascript', array('conditional' => 'gte IE 8',))
            ->appendFile($this->basePath() . '/js/bootstrap-alert.js')
            ->appendFile($this->basePath() . '/js/bootstrap-confirmation.js')
            // https://github.com/Tavicu/bootstrap-confirmation
            ->appendFile($this->basePath() . '/js/jquery.bootstrap.wizard.js')
            // https://github.com/VinceG/twitter-bootstrap-wizard
            ->appendFile($this->basePath() . '/js/script.js', 'text/javascript')
        ;?>
        
<?php echo $this->headStyle(); ?>

    </head>
    <body class="body-bg">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
            
                <div class="navbar-header">
                    <!--.nav-toggle -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--/.nav-toggle -->
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" style="max-height:20px;" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Caronte')?> - <?php echo $this->translate('Assistenza Tecnica')?></a>
                </div>
                <!--.nav-collapse -->
                <div class="collapse navbar-collapse">
                    <!-- <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?><span class="sr-only">(current)</span></a></li>
                    </ul> -->
                    
                    <ul class="nav navbar-nav navbar-right">
                        <?php // Retrive current view & page 
            				$view = current($this->viewModel()->getCurrent()->getChildren());?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
                                style="color: #9cf; background-color:#555; border-radius:10px; padding:8px; margin:7px 0px;">
                                <span class="glyphicon glyphicon-user"></span>&nbsp;<span id="name"><?php echo $view->name; ?></span>&nbsp;<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#" onclick="return content();"><span class="glyphicon glyphicon-refresh"></span> <?php echo $this->translate('Aggiorna') ?></a></li>
                                <li class="divider"></li>
                                <li><a data-toggle="modal" data-backdrop="static" data-keyboard="false" href="#settings"><span class="glyphicon glyphicon-cog"></span> <?php echo $this->translate('Configurazioni') ?></a></li>
                                <li><a href="<?php echo $this->url('logout')?>"><span class="glyphicon glyphicon-log-out"></span> <?php echo $this->translate('Esci') ?></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <div class="modal modal-wait"></div>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zenatek S.P.A. <?php echo $this->translate('Tutti i diritti riservati.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php if (isset($view->modals)) foreach ($view->modals as $modal) {
        	echo $this->partial($modal['modalName'] , $modal['modalParams']);
		} ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
