<?php $style_ie7 =
".titleBox span:first-child {
	float: left !important;
}
#ambitoApplicativo li span[class!='glyphicon'] {
    float: left !important;
}";
$this->headStyle()->appendStyle($style_ie7, array('conditional' => 'IE 7'));
$this->headScript ()->appendFile($this->basePath() . '/js/home.js')
?>

<script type="text/javascript">
<!--
/* Function Colorize */
var palette = {
		"color-0" : "bg-r",
		"color-1" : "bg-dark-r"
};
/* Function initHelp */
var ambitiApplicativiHelps = {
		title_0: "<b>Ambiti Applicativi</b><br />rappresentano le categorie a cui le segnalazioni appartengono" ,
		title_1: "Per ogni Ambito Applicativo è possibile creare <button class='btn btn-xxs btn-primary'><span class='glyphicon glyphicon-plus'></span></button> e monitorare le proprie segnalazioni in <span class='badge alert-warning'>In Lavorazione</span> e <span class='badge alert-success'>Chiuse</span>" ,
};
var bozzeHelps = {
		title_0: "<b>In Lavorazione</b><br />contengono le segnalazioni pubblicate <button class='btn btn-xxs btn-info'><span class='glyphicon glyphicon-send'></span></button> per tutte le fasi di avanzamenti fino alla chiusura",
		title_1: "Il colore del tag <span class='badge'><span class='glyphicon glyphicon-tag'></span></span> determina l'Ambito Applicativo di appartenenza",
		title_2: "E' possibile aprire <button class='btn btn-xxs btn-default'><span class='glyphicon glyphicon-zoom-in'></span></button> le segnalazioni per consultare il loro stato di avanzamento <span class='badge alert-info'><span class='glyphicon glyphicon-comment'></span></span>",
};
var chiuseHelps = {
		title_0: "<b>Chiuse</b><br />contiene segnalazioni in fine avanzamento e risolte <span class='badge alert-success'><span class='glyphicon glyphicon-ok'></span></span> dagli operatori di supporto",
		title_1: "Il colore del tag <span class='badge'><span class='glyphicon glyphicon-tag'></span></span> determina l'Ambito Applicativo di appartenenza",
		title_2: "E' possibile aprire <button class='btn btn-xxs btn-default'><span class='glyphicon glyphicon-zoom-in'></span></button> le segnalazioni per consultare si sono consluse <span class='badge alert-info'><span class='glyphicon glyphicon-comment'></span></span>",
};
var legendaHelps = {
		title: "<b>Legenda</b><br />contiene suggerimenti e chiarisce ogni bottone o icona.<br />Ogni <b>Sezione</b> <span class='glyphicon glyphicon-chevron-down'></span> è espandibile"
};
/* Function Populate */
var bozzeStateIds = <?php echo json_encode($this->otrsInlav)?>;
var chiuseStateIds = <?php echo json_encode($this->otrsChiuse)?>;
/* Function Content */
var content_url = "<?php echo $this->url('test', array('controller' => 'frontend', 'action'=>'ticketLists'))?>";

$(function () {
    content();
});
//-->
</script>

<div class="container">

<span id="feedback"></span>

<div class="row">

<!-- <div id="bacheca" class="col-md-12">
    </div>
</div> -->

<div id="ambitiApplicativi" class="col-md-3 colBox">
<div class="well titleBox bg-rgb">
    <span>Ambiti Applicativi</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
<?php foreach ($this->queues as $queue): ?>
    <li id="q<?php echo $queue['order']; ?>" class="color-<?php echo $queue['order']; ?>">
        <p><?php echo $queue['name']; ?></p>
        <ol><li>
            <a href="#inLavorazione"><span id="q<?php echo $queue['order']; ?>_bozze" data-name="counter" title="segnalazioni in lavorazione" class="badge alert-warning">N</span></a>
            <a href="#chiuse"><span id="q<?php echo $queue['order']; ?>_chiuse" data-name="counter" title="segnalazioni chiuse" class="badge alert-success">N</span></a>
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="btn btn-xs btn-primary"
                    data-service-id="<?php echo $queue['service_id']; ?>" data-queue-id="<?php echo $queue['id']; ?>"
                    data-queue-name="<?php echo $queue['name']; ?>" data-queue-color="color-<?php echo $queue['order']; ?>"
                    data-id="0" data-ticket-priority="0" data-articles="0" data-ticket-desc="" >
                    <span title="apri una nuova segnalazione" class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </li></ol>
    </li>
<?php endforeach; ?>
</ol>
</div>

<div id="bozze" class="col-md-3 colBox">
<div id="inLavorazione" class="well titleBox bg-rg">
    <span class="">In Lavorazione <span id="tot_bozze" data-name="counter" title="totale" class="badge">N</span></span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
    <li id="bozze_empty"><center><i>Vuoto</i></center></li>
    <li data-ticket-id="0" class="bozze-ticket hidden bg-rgb">
    <span data-name="Title">Default Title</span>
    <span class="badge queue-color pull-right"><span data-name="QueueName" data-prop="title" title="Default Queue" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-info"><span data-name="ArticleNum">?</span> <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <!-- span class="badge alert-info"><span  data-name="AttachmentNum">?</span> <span title="allegati" class="glyphicon glyphicon-paperclip"></span></span -->
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="pull-right btn btn-xs btn-default"
                    data-service-id="0" data-queue-id="0" data-queue-name="Default Queue" data-queue-color="color-?"
                    data-ticket-title="Default Title" data-ticket-desc="Default Desc" data-ticket-priority="0" data-articles="0"
                ><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
    
</ol>

</div>

<div id="chiuse" class="col-md-3 colBox">
<div class="well titleBox bg-g">
    <span class="">Chiuse <span id="tot_chiuse" data-name="counter" title="totale" class="badge">N</span></span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
<!--     <form class="form-inline filter" role="form"> -->
<!--         <div class="input-group"> -->
<!--             <input type="text" class="form-control" id="filterSearch" placeholder="Filtro di ricerca..."> -->
<!--             <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span> -->
<!--         </div> -->
<!--         <center class="small">2 segnalazioni trovate</center> -->
<!--     </form> -->
    <li id="chiuse_empty"><center><i>Vuoto</i></center></li>
    <li data-ticket-id="0" class="chiuse-ticket hidden bg-rgb">
    <span data-name="Title">Default Title</span>
    <span class="badge queue-color pull-right"><span data-name="QueueName" data-prop="title" title="Default Queue" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-success"><span title="risolta con successo" class="glyphicon glyphicon-ok"></span></span>
            <span class="badge alert-info"><span data-name="ArticleNum">?</span> <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <!-- span class="badge alert-info"><span  data-name="AttachmentNum">?</span> <span title="allegati" class="glyphicon glyphicon-paperclip"></span></span -->
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="pull-right btn btn-xs btn-default"
                    data-queue-id="0" data-queue-name="Default Queue" data-queue-color="color-?"
                    data-ticket-title="Default Title" data-ticket-desc="Default Desc" data-ticket-priority="0" data-articles="0"
                ><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
</ol>
</div>

<div id="legenda" class="col-md-3 colBox">
<div class="well titleBox bg-rgb">
    <span>Legenda</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingZero">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseZero" aria-expanded="true" aria-controls="collapseZero">
          Guida introduttiva
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseZero" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingZero">
      <div class="panel-body">
        <ul>
            <li>Ogni sezione prevede una guida <span class="small glyphicon glyphicon-question-sign"></span> che aiuta a capirne il significato</li>
            <li>Posizionando il mouse sopra a <span class="small glyphicon glyphicon-question-sign"></span> è possibile leggerne il contenuto</li>
            <li>Quando la guida è <span class="small glyphicon glyphicon-question-sign alert-warning"></span>, è possibile clickare e leggere più suggerimenti</li>
        </ul>
      </div>
    </div>
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Ambiti Applicativi
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <p>
            &nbsp;<span class="glyphicon glyphicon-warning-sign alert-danger"></span>&nbsp; Nuove segnalazioni bloccate
        </p>
        <p>
            <span class="badge alert-warning">N</span> <b>N</b> Segnalazioni in Lavorazione
        </p>
        <p>
            <span class="badge alert-success">N</span> <b>N</b> Segnalazioni Chiuse
        </p>
        <p>
            <button class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-plus"></span></button> Nuova segnalazione
        </p>
      </div>
    </div>
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          In Lavorazione
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <p>
            <span class="badge"><span class="glyphicon glyphicon-tag"></span></span> Colore di Ambito Applicativo
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-comment"></span></span> <b>N</b> Articoli
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-paperclip"></span></span> <b>N</b> Allegati <small>(non attivo nella demo)</small>
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-zoom-in"></span></button> Visualizza la segnalazione
        </p>
     </div>
    </div>
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Chiuse
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        <p>
            <span class="badge"><span class="glyphicon glyphicon-tag"></span></span> Colore di Ambito Applicativo
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-search"></span></button> Filtra la lista <small>(non attivo nella demo)</small>
        </p>
        <p>
            <span class="badge alert-success"><span class="glyphicon glyphicon-ok"></span></span> Risolta con successo
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-comment"></span></span> <b>N</b> Articoli
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-paperclip"></span></span> <b>N</b> Allegati <small>(non attivo nella demo)</small>
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-zoom-in"></span></button> Visualizza segnalazione
        </p>
      </div>
    </div>
  </div>
</div>
</div> 

</div>
</div>
</div>