<?php $style_ie7 =
".titleBox span:first-child {
	float: left !important;
}
#ambitoApplicativo li span[class!='glyphicon'] {
    float: left !important;
}";
$this->headStyle()->appendStyle($style_ie7, array('conditional' => 'IE 7'));?>

<script type="text/javascript">
<!--
var palette = {
		"color-0" : "bg-r",
		"color-1" : "bg-dark-r"
};

var ambitiApplicativiHelps = {
		title_0: "<b>Ambiti Applicativi</b><br />rappresentano le categorie a cui le segnalazioni appartengono" ,
		title_1: "Per ogni Ambito Applicativo è possibile creare <button class='btn btn-xxs btn-primary'><span class='glyphicon glyphicon-plus'></span></button> e monitorare le proprie segnalazioni in <span class='badge alert-warning'>In Lavorazione</span> e <span class='badge alert-success'>Chiuse</span>" ,
};

var bozzeHelps = {
		title_0: "<b>In Lavorazione</b><br />contengono le segnalazioni pubblicate <button class='btn btn-xxs btn-info'><span class='glyphicon glyphicon-send'></span></button> per tutte le fasi di avanzamenti fino alla chiusura",
		title_1: "Il colore del tag <span class='badge'><span class='glyphicon glyphicon-tag'></span></span> determina l'Ambito Applicativo di appartenenza",
		title_2: "E' possibile aprire <button class='btn btn-xxs btn-default'><span class='glyphicon glyphicon-zoom-in'></span></button> le segnalazioni per consultare il loro stato di avanzamento <span class='badge alert-info'><span class='glyphicon glyphicon-comment'></span></span>",
};

var chiuseHelps = {
		title_0: "<b>Chiuse</b><br />contiene segnalazioni in fine avanzamento e risolte <span class='badge alert-success'><span class='glyphicon glyphicon-ok'></span></span> dagli operatori di supporto",
		title_1: "Il colore del tag <span class='badge'><span class='glyphicon glyphicon-tag'></span></span> determina l'Ambito Applicativo di appartenenza",
		title_2: "E' possibile aprire <button class='btn btn-xxs btn-default'><span class='glyphicon glyphicon-zoom-in'></span></button> le segnalazioni per consultare si sono consluse <span class='badge alert-info'><span class='glyphicon glyphicon-comment'></span></span>",
};

var legendaHelps = {
		title: "<b>Legenda</b><br />contiene suggerimenti e chiarisce ogni bottone o icona.<br />Ogni <b>Sezione</b> <span class='glyphicon glyphicon-chevron-down'></span> è espandibile"
};


function removeColors (index, css) {
    return (css.match (/(^|\s)bg-\S+/g) || []).join(' ');
}

function removeMetaColors (index, css) {
    return (css.match (/(^|\s)color-\S+/g) || []).join(' ');
}

function colorize($scope)
{
	var $target = $scope || $(document);
	$.each(palette, function (index, value){
		var $items = $target.find('.'+index);
		$items.removeClass(removeColors)
            .addClass(value);
	});
	return true;
}

function initHelp() // called from script.js
{
	$.each( ambitiApplicativiHelps, function(index, value){
		   $('#ambitiApplicativi span[data-toggle="tooltip"]').attr(index, value);
    });
	$.each( bozzeHelps, function(index, value){
		   $('#bozze span[data-toggle="tooltip"]').attr(index, value);
    });
	$.each( chiuseHelps, function(index, value){
		   $('#chiuse span[data-toggle="tooltip"]').attr(index, value);
	});
	$.each( legendaHelps, function(index, value){
		   $('#legenda span[data-toggle="tooltip"]').attr(index, value);
	});
}

function updateTicket(v, $li){
	$li.attr('data-ticket-id', v['TicketID']);
	$li.find('*[data-name="Title"]').not('[data-prop]').empty().html(v['Title']);
	$li.find('*[data-name="ArticleNum"]').not('[data-prop]').empty().html(v['ArticleNum']);
	$li.find('.queue-color').removeClass(removeMetaColors).addClass(v['QueueColor']);
	$li.find('*[data-name="QueueName"][data-prop]').each(function(){
		$(this).prop($(this).data('prop'), v['QueueName']);});

	var $button = $li.find('button[data-toggle]');
	$button.attr('data-queue-id', v['QueueID']);
	$button.attr('data-queue-name', v['QueueName']);
	$button.attr('data-queue-color', v['QueueColor']);
	$button.attr('data-id', v['TicketID']);
	$button.prop('data-ticket-priority', parseInt(v['Article'][0]['PriorityID']) >= 4);
	$button.prop('data-ticket-title', v['Title']);
	$button.prop('data-ticket-desc', v['Article'][0]['Body']);
}

function populate(data){
	var bozzeStateIds = <?php echo json_encode($this->otrsInlav)?>;
    var chiuseStateIds = <?php echo json_encode($this->otrsChiuse)?>;
    var bozze = [], chiuse = [];
    var $bozzeTicket = $('.bozze-ticket');    
    var $chiuseTicket = $('.chiuse-ticket');
    var counters = {};

    // generazione liste di visualizzazione
    $.each(bozzeStateIds, function(k,id){
        if(id in data) $.merge(bozze, data[id]);});
    $.each(chiuseStateIds, function(k,id){
        if(id in data) $.merge(chiuse, data[id]);});

    // aggiornamento contatori
    $.each(bozze, function(k,v){
    		var id = 'q'+v['QueueOrder']+'_bozze';
    		counters[id] = (id in counters)?counters[id]+1:1;
		});
    $.each(chiuse, function(k,v){
			var id = 'q'+v['QueueOrder']+'_chiuse';
			counters[id] = (id in counters)?counters[id]+1:1;
		});
    $.each(counters, function(k,v){
    	$('#'+k).text(v+"");});
    
    var $bozzeMsg = (bozze.length)? $('#bozze_empty').fadeOut() : $('#bozze_empty').fadeIn();
    var $chiuseMsg = (chiuse.length)? $('#chiuse_empty').fadeOut() : $('#chiuse_empty').fadeIn();

    var $currentList = [];
	$.each(bozze, function(k,v){
    		var $li = $bozzeTicket.siblings("li[data-ticket-id='"+v['TicketID']+"']");
    		if ($li.length){
    			// update
    			updateTicket(v, $li);
    			$bozzeTicket.before($li);
    		}else{
    			// create		  
		        $li = $bozzeTicket.clone();
		        $bozzeTicket.before($li);
		        $li.removeClass('bozze-ticket');
		        $li.toggleClass('hidden');
		        updateTicket(v, $li);
    		}
    		$.merge($currentList,$li);
		});
	$bozzeTicket.siblings("li").not($currentList).remove();
}

function content(){
	$.ajax({
		url:			"<?php echo $this->url('test', array('controller' => 'frontend', 'action'=>'ticketLists'))?>",
		type:			"POST",
		datatype:		"json",
		data:{
			unsername:		$('#auth_username').val(),
		},
		async: true, // default true
		success: function(data, status) {
			console.log(data); // for debugging
			populate(data);
			colorize();
		},
		error: function(data, status) { console.log('<ajaxConsole ERROR> '+data+' <ajaxConsole ERROR>'); },
		});
}

$(function () {
    content();
});
//-->
</script>

<div class="container">

<span id="feedback"></span>

<div class="row">

<!-- <div id="bacheca" class="col-md-12">
    </div>
</div> -->

<div id="ambitiApplicativi" class="col-md-3 colBox">
<div class="well titleBox bg-rgb">
    <span>Ambiti Applicativi</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
<?php foreach ($this->queues as $queue): ?>
    <li id="q<?php echo $queue['order']; ?>" class="color-<?php echo $queue['order']; ?>">
        <p><?php echo $queue['name']; ?></p>
        <ol><li>
            <a href="#inLavorazione"><span id="q<?php echo $queue['order']; ?>_bozze" title="segnalazioni in lavorazione" class="badge alert-warning">N</span></a>
            <a href="#chiuse"><span id="q<?php echo $queue['order']; ?>_chiuse" title="segnalazioni chiuse" class="badge alert-success">N</span></a>
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="btn btn-xs btn-primary"
                    data-queue-id="<?php echo $queue['id']; ?>" data-queue-name="<?php echo $queue['name']; ?>"
                    data-queue-color="color-<?php echo $queue['order']; ?>" data-id="0"
                    data-ticket-priority="0" data-ticket-desc="" >
                    <span title="apri una nuova segnalazione" class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </li></ol>
    </li>
<?php endforeach; ?>
</ol>
</div>

<div id="bozze" class="col-md-3 colBox">
<div id="inLavorazione" class="well titleBox bg-rg">
    <span class="">In Lavorazione</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
    <li id="bozze_empty"><center><i>Vuoto</i></center></li>
    <li data-ticket-id="0" class="bozze-ticket hidden bg-rgb">
    <span data-name="Title">Default Title</span>
    <span class="badge queue-color pull-right"><span data-name="QueueName" data-prop="title" title="Default Queue" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-info"><span data-name="ArticleNum">?</span> <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <!-- span class="badge alert-info"><span  data-name="AttachmentNum">?</span> <span title="allegati" class="glyphicon glyphicon-paperclip"></span></span -->
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="pull-right btn btn-xs btn-default"
                    data-queue-id="0" data-queue-name="Default Queue" data-queue-color="color-?"
                    data-ticket-title="Default Title" data-ticket-desc="Default Desc" data-ticket-priority="0"
                ><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
    
</ol>

</div>

<div id="chiuse" class="col-md-3 colBox">
<div class="well titleBox bg-g">
    <span class="">Chiuse</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
<!--     <form class="form-inline filter" role="form"> -->
<!--         <div class="input-group"> -->
<!--             <input type="text" class="form-control" id="filterSearch" placeholder="Filtro di ricerca..."> -->
<!--             <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span> -->
<!--         </div> -->
<!--         <center class="small">2 segnalazioni trovate</center> -->
<!--     </form> -->
    <li class="bg-rgb">
        Messaggio di errore
        <span class="badge bg-r pull-right"><span title="Presidio MQ" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-success"><span title="risolta con successo" class="glyphicon glyphicon-ok"></span></span>
            <span class="badge alert-info">3 <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <div class="pull-right">
                <button class="pull-right btn btn-xs btn-default"><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
    <li class="bg-rgb">
        Batch troppo lento
        <span class="badge bg-dark-b pull-right"><span title="Cassa Centrale" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-success"><span title="risolta con successo" class="glyphicon glyphicon-ok"></span></span>
            <span class="badge alert-info">5 <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <div class="pull-right">
                <button class="pull-right btn btn-xs btn-default"><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
</ol>
</div>

<div id="legenda" class="col-md-3 colBox">
<div class="well titleBox bg-rgb">
    <span>Legenda</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingZero">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseZero" aria-expanded="true" aria-controls="collapseZero">
          Guida introduttiva
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseZero" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingZero">
      <div class="panel-body">
        <ul>
            <li>Ogni sezione prevede una guida <span class="small glyphicon glyphicon-question-sign"></span> che aiuta a capirne il significato</li>
            <li>Posizionando il mouse sopra a <span class="small glyphicon glyphicon-question-sign"></span> è possibile leggerne il contenuto</li>
            <li>Quando la guida è <span class="small glyphicon glyphicon-question-sign alert-warning"></span>, è possibile clickare e leggere più suggerimenti</li>
        </ul>
      </div>
    </div>
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Ambiti Applicativi
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <p>
            &nbsp;<span class="glyphicon glyphicon-warning-sign alert-danger"></span>&nbsp; Nuove segnalazioni bloccate
        </p>
        <p>
            <span class="badge alert-warning">N</span> <b>N</b> Segnalazioni in Lavorazione
        </p>
        <p>
            <span class="badge alert-success">N</span> <b>N</b> Segnalazioni Chiuse
        </p>
        <p>
            <button class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-plus"></span></button> Nuova segnalazione
        </p>
      </div>
    </div>
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          In Lavorazione
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <p>
            <span class="badge"><span class="glyphicon glyphicon-tag"></span></span> Colore di Ambito Applicativo
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-comment"></span></span> <b>N</b> Articoli
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-paperclip"></span></span> <b>N</b> Allegati <small>(non attivo nella demo)</small>
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-zoom-in"></span></button> Visualizza la segnalazione
        </p>
     </div>
    </div>
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Chiuse
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        <p>
            <span class="badge"><span class="glyphicon glyphicon-tag"></span></span> Colore di Ambito Applicativo
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-search"></span></button> Filtra la lista <small>(non attivo nella demo)</small>
        </p>
        <p>
            <span class="badge alert-success"><span class="glyphicon glyphicon-ok"></span></span> Risolta con successo
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-comment"></span></span> <b>N</b> Articoli
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-paperclip"></span></span> <b>N</b> Allegati <small>(non attivo nella demo)</small>
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-zoom-in"></span></button> Visualizza segnalazione
        </p>
      </div>
    </div>
  </div>
</div>
</div> 

</div>
</div>
</div>