<script type="text/javascript">
<!--
//-->
</script>


<div class="container">
<div class="row">
<div class="col-md-12">
    <div class="bacheca">
        <div>
        Bacheca
        </div>
    </div>
</div>

<div id="ambitoApplicativo" class="col-md-3">
<div class="well titleBox">
    <span class="pull-left">Ambito Applicativo</span>
    <abbr class="pull-right" title="Premere il bottone [Aggiungi] dell'ambito applicativo
al quale si vuole aprire una nuova segnalazione">
        <span class="small glyphicon glyphicon-question-sign alert-warning blink"></span>
    </abbr>
</div>
<ol class="well sortable simple_with_no_drop bugsBox">
    <li class="highlight">
    First
    <ol></ol>
    </li>
    <li>
    Second
    <ol></ol>
    </li>
    <li>
    Third
        <ol>
          <li class="">First</li><li>Second</li>
          <li>
            Third
            <ol>
              
              <li class="">First</li><li>Second</li>
            </ol>
            <ol>
              <li>First</li>
              <li>Second</li>
            </ol>
          </li>
        </ol>
    </li>
    <li>Fourth</li>
    <li>Fifth</li>
    <li>Sixth</li>
</ol>
</div>

<div class="col-md-3">
<div class="well titleBox">
    <span class="pull-left">Segnalazioni in Bozza</span>
    <abbr class="pull-right" title="Premere il bottone [Aggiungi] dell'ambito applicativo
al quale si vuole aprire una nuova segnalazione">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </abbr>
</div>
<ol class="sortable well simple_with_drop bugsBox">
    <li>
    First
    <ol></ol>
    </li>
    <li>
    Second
    <ol></ol>
    </li>
    <li>
    Third
        <ol>
          
          <li class="">First</li><li>Second</li>
          <li>
            Third
            <ol>
              
              <li class="">First</li><li>Second</li>
            </ol>
            <ol>
              <li>First</li>
              <li>Second</li>
            </ol>
          </li>
        </ol>
    </li>
    <li>Fourth</li>
    <li>Fifth</li>
    <li>Sixth</li>
</ol>
</div>

<div class="col-md-3">
<div class="well titleBox sidebar-offcanvas">
    <span class="pull-left">Segnalazioni Pubbliche</span>
    <abbr class="pull-right" title="Premere il bottone [Aggiungi] dell'ambito applicativo
al quale si vuole aprire una nuova segnalazione">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </abbr>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
    <li>
    First
    <ol></ol>
    </li>
    <li>
    Second
    <ol></ol>
    </li>
    <li>
    Third
        <ol>
          
          <li class="">First</li><li>Second</li>
          <li>
            Third
            <ol>
              
              <li class="">First</li><li>Second</li>
            </ol>
            <ol>
              <li>First</li>
              <li>Second</li>
            </ol>
          </li>
        </ol>
    </li>
    <li class="highlight">Fourth</li>
    <li>Fifth</li>
    <li>Sixth</li>
</ol>
</div>

<div class="col-md-3">
<div class="well titleBox">
    <span class="pull-left">Legenda</span>
    <abbr class="pull-right" title="Premere il bottone [Aggiungi] dell'ambito applicativo
al quale si vuole aprire una nuova segnalazione">
        <span class="small glyphicon glyphicon-question-sign"></span>
    </abbr>
</div>
<ol class="well sortable bugsBox">
    <li>
        First
    </li>
</ol>
</div> 
</div>

</div>
</div>