<?php $style_ie7 =
".titleBox span:first-child {
	float: left !important;
}
#ambitoApplicativo li span[class!='glyphicon'] {
    float: left !important;
}";
$this->headStyle()->appendStyle($style_ie7, array('conditional' => 'IE 7'));?>

<script type="text/javascript">
<!--
//-->
</script>

<div class="container">

<span id="feedback"></span>

<div class="row">

<!-- <div id="bacheca" class="col-md-12">
    </div>
</div> -->

<div id="ambitiApplicativi" class="col-md-3 colBox">
<div class="well titleBox bg-rgb">
    <span>Ambiti Applicativi</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left"
        >
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
<!--     <abbr class="pull-right" title="Premere il bottone [Aggiungi] dell'ambito applicativo -->
<!-- al quale si vuole aprire una nuova segnalazione"> -->
<!--         <span class="small glyphicon glyphicon-question-sign alert-warning blink"></span> -->
<!--     </abbr> -->
</div>
<ol class="well sortable simple_with_no_drop bugsBox">
    <li class="bg-r">
        <p>Presidio MQ</p>
        <ol><li>
            <span title="nuove segnalazioni bloccate" class="glyphicon glyphicon-warning-sign alert-danger"></span>
            <a href="#inLavorazione"><span  title="segnalazioni in lavorazione" class="badge alert-warning">1</span></a>
            <a href="#chiuse"><span  title="segnalazioni chiuse" class="badge alert-success">1</span></a>
            <div class="pull-right">
                <button disabled="disabled" data-toggle="modal" data-target="#ticketModal" class="btn btn-xs btn-primary">
                    <span title="apri una nuova segnalazione" class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </li></ol>
    </li>
    <li class="bg-dark-r">
        <p>EasyPOP</p>
        <ol><li>
            <a href="#bozze"><span title="segnalazioni in bozze" class="badge">1</span></a>
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="btn btn-xs btn-primary">
                    <span title="apri una nuova segnalazione" class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </li></ol>
    </li>
    <li class="bg-dark-rb">
        <p>Supporto Sistemi</p>
        <ol><li>
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="btn btn-xs btn-primary">
                    <span title="apri una nuova segnalazione" class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </li></ol>
    </li>
    <li class="bg-dark-b">
        <p>Cassa Centrale</p>
        <ol><li>
            <a href="#inLavorazione"><span title="segnalazioni in lavorazione" class="badge alert-warning">1</span></a>
            <a href="#chiuse"><span title="segnalazioni chiuse" class="badge alert-success">1</span></a>
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="btn btn-xs btn-primary">
                    <span title="apri una nuova segnalazione" class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </li></ol>
    </li>
    <li class="bg-gb">
        <p>ContPV</p>
        <ol><li>
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="btn btn-xs btn-primary">
                    <span title="apri una nuova segnalazione" class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </li></ol>
    </li>
    <li class="bg-dark-rg">
        <p>Gratta & Vinci</p>
        <ol><li>
            <div class="pull-right">
                <button data-toggle="modal" data-target="#ticketModal" class="btn btn-xs btn-primary">
                    <span title="apri una nuova segnalazione" class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </li></ol>
    </li>
</ol>
</div>

<div id="bozze" class="col-md-3 colBox">

<div id="inLavorazione" class="well titleBox bg-rg">
    <span class="">In Lavorazione</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left"
    >
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
    <li class="bg-rgb">
    Ordini magazzino lenti
    <span class="badge bg-r pull-right"><span title="Presidio MQ" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-info">5 <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <span class="badge alert-info">2 <span title="allegati" class="glyphicon glyphicon-paperclip"></span></span>
            <div class="pull-right">
                <button class="pull-right btn btn-xs btn-default"><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
    <li class="bg-rgb">
    Iva assolta alla fonte
    <span class="badge bg-dark-b pull-right"><span title="Cassa Centrale" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-info">2 <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <div class="pull-right">
                <button class="pull-right btn btn-xs btn-default"><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
</ol>

</div>

<div id="chiuse" class="col-md-3 colBox">
<div class="well titleBox bg-g">
    <span class="">Chiuse</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left"
    >
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>
<ol class="well sortable simple_with_no_drag bugsBox">
<!--     <form class="form-inline filter" role="form"> -->
<!--         <div class="input-group"> -->
<!--             <input type="text" class="form-control" id="filterSearch" placeholder="Filtro di ricerca..."> -->
<!--             <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span> -->
<!--         </div> -->
<!--         <center class="small">2 segnalazioni trovate</center> -->
<!--     </form> -->
    <li class="bg-rgb">
        Messaggio di errore
        <span class="badge bg-r pull-right"><span title="Presidio MQ" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-success"><span title="risolta con successo" class="glyphicon glyphicon-ok"></span></span>
            <span class="badge alert-info">3 <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <div class="pull-right">
                <button class="pull-right btn btn-xs btn-default"><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
    <li class="bg-rgb">
        Batch troppo lento
        <span class="badge bg-dark-b pull-right"><span title="Cassa Centrale" class="glyphicon glyphicon-tag"></span></span>
        <ol><li>
            <span class="badge alert-success"><span title="risolta con successo" class="glyphicon glyphicon-ok"></span></span>
            <span class="badge alert-info">5 <span title="articoli" class="glyphicon glyphicon-comment"></span></span>
            <div class="pull-right">
                <button class="pull-right btn btn-xs btn-default"><span title="apri" class="glyphicon glyphicon-zoom-in"></span></button>
            </div>
        </li></ol>
    </li>
</ol>
</div>

<div id="legenda" class="col-md-3 colBox">
<div class="well titleBox bg-rgb">
    <span>Legenda</span>
    <span class="pull-right" data-toggle="tooltip" data-placement="left"
    >
        <span class="small glyphicon glyphicon-question-sign"></span>
    </span>
</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingZero">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseZero" aria-expanded="true" aria-controls="collapseZero">
          Guida introduttiva
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseZero" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingZero">
      <div class="panel-body">
        <ul>
            <li>Ogni sezione prevede una guida <span class="small glyphicon glyphicon-question-sign"></span> che aiuta a capirne il significato</li>
            <li>Posizionando il mouse sopra a <span class="small glyphicon glyphicon-question-sign"></span> è possibile leggerne il contenuto</li>
            <li>Quando la guida è <span class="small glyphicon glyphicon-question-sign alert-warning"></span>, è possibile clickare e leggere più suggerimenti</li>
        </ul>
      </div>
    </div>
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Ambiti Applicativi
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <p>
            &nbsp;<span class="glyphicon glyphicon-warning-sign alert-danger"></span>&nbsp; Nuove segnalazioni bloccate
        </p>
        <p>
            <span class="badge alert-warning">N</span> <b>N</b> Segnalazioni in Lavorazione
        </p>
        <p>
            <span class="badge alert-success">N</span> <b>N</b> Segnalazioni Chiuse
        </p>
        <p>
            <button class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-plus"></span></button> Nuova segnalazione
        </p>
      </div>
    </div>
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          In Lavorazione
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <p>
            <span class="badge"><span class="glyphicon glyphicon-tag"></span></span> Colore di Ambito Applicativo
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-comment"></span></span> <b>N</b> Articoli
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-paperclip"></span></span> <b>N</b> Allegati
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-zoom-in"></span></button> Visualizza la segnalazione
        </p>
     </div>
    </div>
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Chiuse
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        <p>
            <span class="badge"><span class="glyphicon glyphicon-tag"></span></span> Colore di Ambito Applicativo
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-search"></span></button> Applica il filtro di ricerca
        </p>
        <p>
            <span class="badge alert-success"><span class="glyphicon glyphicon-ok"></span></span> Risolta con successo
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-comment"></span></span> <b>N</b> Articoli
        </p>
        <p>
            <span class="badge alert-info">N <span class="glyphicon glyphicon-paperclip"></span></span> <b>N</b> Allegati
        </p>
        <p>
            <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-zoom-in"></span></button> Visualizza segnalazione
        </p>
      </div>
    </div>
  </div>
</div>
</div> 

</div>
</div>
</div>